=== Yan3ku/WAI-1/index.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:attribute name="title" type="shortString" />
    <xs:attribute name="lang" type="langType" />

    <xs:attributeGroup name="textData">
        <xs:attribute ref="title" use="required" />
        <xs:attribute ref="lang" />
    </xs:attributeGroup>

    <xs:element name="page" type="pageType" />

    <xs:simpleType name="coordinates">
        <xs:list itemType="xs:double"></xs:list>
    </xs:simpleType>

    <xs:element name="id">
        <xs:simpleType>
            <xs:union memberTypes="idbyno idbystring" />
        </xs:simpleType>
    </xs:element>

    <xs:simpleType name="idbyno">
        <xs:restriction base="xs:positiveInteger">
            <xs:maxInclusive value="999" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idbystring">
        <xs:restriction base="xs:string">
            <xs:pattern value="#[0-9]+"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="pageType">
        <xs:sequence>
            <xs:element name="author">
                <xs:complexType>
                    <xs:all>
                        <xs:element ref="id"></xs:element>
                        <xs:element name="name">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[a-zA-Z]+" />
                                    <xs:maxLength value="128"></xs:maxLength>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="date">
                            <xs:simpleType>
                                <xs:restriction base="xs:date">
                                    <xs:minInclusive value="1920-01-01" />
                                    <xs:maxInclusive value="2025-12-31" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="updatedCount">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="encoding">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="utf-8" />
                                    <xs:enumeration value="utf-16" />
                                    <xs:enumeration value="iso1925" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="cords" type="coordinates"></xs:element>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element name="subpage" type="subpageType" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attributeGroup ref="textData" />
    </xs:complexType>

    <xs:complexType name="subpageType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="section" type="sectionType" maxOccurs="unbounded" />
            <xs:element ref="form"/>
        </xs:choice>
        <xs:attributeGroup ref="textData" />
        <xs:attribute name="is-index" type="indexType" />
        <xs:attribute name="easter-egg" type="easterEggType" />
        <xs:attribute name="coolness" type="coolnessLevelType" default="0" />
    </xs:complexType>
    
    <xs:complexType name="sectionType">
        <xs:sequence>
            <xs:element name="about" type="xs:string" minOccurs="0" />
            <xs:element name="persons" type="personsType" minOccurs="0" />
            <xs:element name="media" type="mediaType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" />
    </xs:complexType>

    <xs:element name="form" type="formType" />

    <xs:complexType name="mediaType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="image" type="adressType" maxOccurs="unbounded"/>
            <xs:element name="video" type="adressType" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="adressType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="link" type="xs:anyURI"/>
                <xs:attribute name="source" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="personsType">
        <xs:sequence>
            <xs:element name="person" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="about" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="gender" type="genderType"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    
    <xs:complexType name="formType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="inputString">
                <xs:complexType>
                    <xs:attribute name="label" type="shortString"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="inputRadio" type="option"/>
            <xs:element name="inputSelection" type="option"/>
        </xs:choice>
        <xs:attribute name="name" type="shortString"/>
    </xs:complexType>
    
    <xs:complexType name="option">
        <xs:sequence>
            <xs:element name="option" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="label"/>
    </xs:complexType>
    
    <xs:simpleType name="genderType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="man"/>
            <xs:enumeration value="IDontKnowWhoIsThatCreature"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="coolnessLevelType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="easterEggType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="shortString">
        <xs:restriction base="xs:string">
            <xs:maxLength value="128"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="langType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="en"/>
            <xs:enumeration value="pl"/>
            <xs:enumeration value="jp"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="indexType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Yan3ku/WAI-1/index.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<page title="The Art of Touge" lang="en" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd">
    <author>
        <name>Yanek</name>
        <date>2023-11-23</date>
        <encoding>utf-8</encoding>
        <cords>23.3 125.3</cords>
        <updatedCount>5</updatedCount>
        <id>#1234</id>
    </author>
    <subpage title="Legenda Fujarskiego" easter-egg="yes" coolness="10">
        <section title="Final moments of Fujarski Showdown">
            <about>
                Tadeusz Fujarski ściga się z Krzysztofem Tatarskim po tym jak jego ojciec -
                Bogdan Fujarski - oferuje mu pełny bak jeśli wygra wyścig z E34. Wszyscy jednak
                spodziewali się spotkać ojca Tadka, który w swoim czasie był legendarnym
                kierowcą Fiata 125p. Krążą pogłoski, że Bogdan ścigał się kiedyś w
                Stratopolonezie, czyli Polonezem z silnikiem Lancii Stratos (a tak naprawdę z
                Ferrari Dino) z tyłu. Jego koledzy zaskoczeni przybyciem Tadeusza są na niego
                wściekli za to, że on przyjechał zamiast jego ojca, ale on ich uspokaja mówiąc,
                że dostarcza pierogi na tej przełęczy już od 5 lat. Oni zaskoczeni tym faktem
                życzą mu powodzenia w wyścigu. Tuż przed wyścigiem poznaje się ze swoim rywalem:
            </about>
            <persons>
                <person gender="man">
                    <name>Tadeusz Fujarski</name>
                    <about>
                        Syn Bodgdana Fujarskiego, dawnego mistrza przełeczy.
                    </about>
                </person>
                <person gender="man">
                    <name>Krzysztofem Tatarskim</name>
                    <about>
                        Wyzywa Fujarskiego na pojedynek zeby udowodnich ze Klub
                        Nocnych Zakapiorów jest najszybszy na wszystkich
                        bieszczadzkich przeleczach.
                    </about>
                </person>
            </persons>
        </section>
    </subpage>

    <subpage title="The Art of Touge" is-index="yes" lang="en">
        <section title="What is Touge?">
            <about>
                Chinese character 峠 touge means literally mountain road or
                pass. Because of Japans unique geography consisting of islands
                nearly 73% of land is mountainius and rugged. Because of this the
                majority of roads in japans consists of sharp turn and hairpins to
                reduce the difference in altitude needed to climb these roads. This
                results in less wear on cars and increased safety due to lower speed
                but ironically creates the perfect scenario for enthusiast to race
                on.
            </about>
            <media>
                <image link="assets/touge.gif" source="Initial D">AE86 vs GT-R battle</image>
                <video link="assets/touge.gif" source="Initial D">AE86 vs GT-R battle</video>
            </media>
        </section>
        
        <section title="History">
            <persons>
                <person>
                    <name>Kunimitsu Takahashi</name>
                    <about>
                        Japanese, motorcycling legend, was the foremost creator
                        of drifting techniques in the 1970s. His legacy
                        popularized the sport and give rise to many 走り屋
                        hashirya, japanese street racers.
                    </about>
                </person>
                <person>
                    <name>Keiichi Tsuchiya </name>
                    <about>
                        Became particularly interested by Takahashi’s early
                        drift techniques and began honing his drifting skills on
                        these same mountain roads and quickly gained a
                        reputation amongst the racing crowd as he took them to
                        the next level. In 1987, several popular car magazines
                        and tuning garages agreed to produce a video of
                        Tsuchiya’s drifting skills in his Toyota AE86 (Corolla).
                        The grainy low budget video, known as Pluspy, became an
                        international hit and inspired many of the professional
                        drifting drivers on the circuits today. Because of his
                        flashy and fast driving Keiichi is known as the ドリフト
                        キング - drift king.
                    </about>
                </person>
            </persons>
            <media>
                <video link="https://youtu.be/p52vfE1ejaA" source="YouTube">Osaka Touge Drifting</video>
                <video link="https://youtu.be/DHOkR8vrP94" source="YouTube">Keiichi Tsuchiya - Pluspy</video>
            </media>
        </section>

        <section title="Cars">
            <about>
                Unlike straight line racing where a lot depends on outright
                power, in Touge racing, other performance aspects will set your
                car apart, especially handling and weight distribution.

                For instance, a small, tossable car like the Toyota MR2, prone
                to snap-oversteer, can beat a stock Mercedes AMG GT-R on a Touge
                course with the proper tuning. The same is true for other
                smaller cars such as the ever-popular AE86 and Honda S2000. Here
                are examples of few iconic Touge cars.
            </about>
            <media>
                <image link="assets/r34" source="local">GT-R</image>
                <image link="assets/supra.jpg" source="local">Supra</image>
            </media>
        </section>

        <form name="Contact Form">
            <inputString label="Name"/>
            <inputString label="Email"/>
            <inputRadio label="Issue">
                <option>Suggestion</option>
                <option>Question</option>
            </inputRadio>
            <inputSelection label="I drive in:">
                <option>video games</option>
                <option>real life</option>
                <option>video games and real life</option>
                <option>I don't drive</option>
            </inputSelection>
        </form>
    </subpage>
</page>
